name: Mac Build

on:
  push:
    branches: [main, experimental]
  pull_request:
    branches: [main, experimental]

  workflow_dispatch:

jobs:
  buildMac:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v2.3.0
      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4
      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp > /dev/null --quiet
          haxe -cp ./setup -D analyzer-optimize -main Main --interp
      - name: Skip SScript setup mode
        run: echo 'oy9:showMacroty8:loopCosti25y10:includeAllfg' >> ~/settings.cocoa
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Compile
        run: haxelib run lime build mac --app-version="4.0.0-${{ github.run_id}}"
      - name: Publish Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: macBuild
          path: export/release/macos/bin
