name: Windows Build

on:
  push:
    branches: [main, experimental]
  pull_request:
    branches: [main, experimental]

  workflow_dispatch:

jobs:
  buildWindows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2.3.0
      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4
      - name: Install Haxelib
        run: |
          haxelib setup C:/haxelib
          haxelib install hxcpp > /dev/null --quiet
      - name: Install Packages (Needed)
        run: |
          haxelib install hmm --quiet
          haxelib run hmm install
        shell: cmd
      - name: Skip SScript setup mode
        run: echo 'oy9:showMacroty8:loopCosti25y10:includeAllfg' >> ~/settings.cocoa
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Compile
        run: haxelib run lime build windows --app-version="4.0.0-${{ github.run_id}}"
      - name: Publish Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: windowsBuild
          path: export/release/windows/bin
